#!/usr/bin/bash
#add a custom header to the nginx servers

echo "
        server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By $HOSTNAME
        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files \$uri \$uri/ =400;
        }
        
        " > /etc/nginx/sites-available/default
service nginx restart
