#!/usr/bin/env bash
#This trap signals 

trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo Y U no love me?!" SIGINT

echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done