#!/usr/bin/env bash
#This init script manages the process manage_my_process

start() {
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "managed_my_process started"
	
}

stop() {
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "mange_my_process stopped"
}

restart() {
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process restarted"
	
}

if (( $# != 1 ))
then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

case "$1" in
start)
start
;;
stop)
stop
;;
restart)
restart
;;
*)
echo "Usage: manage_my_process {start|stop|restart}"

esac
