#!/usr/bin/env bash
#This is a shell script

for (( i=0; i<101; i++))
do
	if (( i % 5 == 0 && i % 3 == 0))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	elif (( i % 3 == 0 ))
	then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
done
